### ISSUE TITLE
MaterialDataTable in a row expanded from another MaterialDataTable don't show data

### ISSUE THREAD

**Issue by diegoe8** [GwtMaterialDesign/gwt-material-table#130]
Hi,
I'm creating DataTables inside another DataTable and data loads correctly, but the child DataTable dont show data in their rows. However, the header and column names shows  data.
I debugged and the data is ok and loaded, but the rows continue in blank.

![image](https://user-images.githubusercontent.com/9061928/34625296-f10531e8-f236-11e7-9f45-979547937873.png)
(Child DataTable with rows in blank)

![image](https://user-images.githubusercontent.com/9061928/34625331-11c37cfa-f237-11e7-80a3-7c74aac29c84.png)
(Debugging the data is ok)

The data in father DataTable are showing ok (photo 1, first row with data) and I'm  creating the child in the same way that I created the father.

Thanks

**Comment by simerlec** [comment]
Hey,

I had the same issue using a table inside a table row expansion. IIRC it had to do with max height. Check for a css rule that sets the max-height to 0.

kr

**Comment by almerlo** [comment]
hi simerlec, thanks for you response. im having the same issue and i checked that. i have max-height in 55px. If i set to 0 or a very large number, nothing happen. Are you sure if the problem has something to do with that css property? 
I was editing the html with chrome developer tool and if i delete the div wich contains the value (ADD000001 in this case), the value is shown ok. I have to delete the div, it is not enough if i delete the css class "cell" only.

Any other idea?

The problem is just with datatable inside a table row expansion. i tried with other controls and it seems to work fine.
![step1](https://user-images.githubusercontent.com/35150400/34627135-2aac672a-f23e-11e7-88d3-1be0f5081943.png)
![step2](https://user-images.githubusercontent.com/35150400/34627136-2ad97026-f23e-11e7-8ed4-1e86689e9282.png)
![sin titulo](https://user-images.githubusercontent.com/35150400/34627137-2b05cd60-f23e-11e7-9867-2f303defab73.png)

**Comment by simerlec** [comment]
Hey @almerlo @diegoe8 

pretty sure that this was the issue here. The div inside the td was getting a `max-height: 0;` which you can see here...

<img width="378" alt="screenshot 2018-01-05 22 27 01" src="https://user-images.githubusercontent.com/5793380/34629205-a3e8d014-f267-11e7-96e2-cd352986e6fb.png">

After overriding the style...

<img width="259" alt="screenshot 2018-01-05 22 29 00" src="https://user-images.githubusercontent.com/5793380/34629275-dcf35f8c-f267-11e7-82f7-d6e0fbff62eb.png">

the text finally showed up :)

Hope this helps.

**Comment by almerlo** [comment]
Mmm. I will keep trying. By the way, what version of GMD are you using?

Thanks

**Comment by simerlec** [comment]
2.0

**Comment by almerlo** [comment]
It works!!!! Thanks simerlec. You saved the week.
