### ISSUE TITLE
Row font color based on row data

### ISSUE THREAD

**Issue by adibacco** [GwtMaterialDesign/gwt-material-table#37]
It would be nice to have the option to change row font color or row background color based on row content. It is possible with the gwt datagrid.

**Comment by brkuntmz** [comment]
You can simply create a custom renderer, and override the 'drawRow' method to define how to render a row based on your specific needs. In order to check row content, you can cast the 'data' parameter of the method to your custom object

    @Override
    public TableRow drawRow(Parameter....parameters){
           
           T data = rowContent.getData();
           ...
           MyCustomObject = (MyCustomObject) data;
           ...
           ---do some checks in the content--
                row.getElement().getStyle().setBackgroundColor('your color preference');
          --end of check--
          ...
    }

At the end, while creating your table, you need to set your custom renderer just as shown in the examples.
     
    table.setRenderer(new CustomRenderer<>());
