### ISSUE TITLE
error in deployed js

### ISSUE THREAD

**Issue by caliny97** [GwtMaterialDesign/gwt-material-table#9]
Great work on this widget. thanks. Running into this weird issue, i tried everything. I am using the material table on a project it runs well on SDM , once is deployed the vertical scroll starts throwing a NPE on every scroll in a infinite data view. here the transpiled js

returnTemp = $onScrollY((lastArg = ($location_0[stackIndex] = 'InfiniteDataView.java:' + '213' , this.$$outer_0) , castToNative(arg0, $wnd.gwt.material.design.jquery.client.api.jQuery) , lastArg)); 

$wnd.gwt is undefined.  Any ideas? 

Thanks a lot.

**Comment by BenDol** [comment]
What version of GWT are you using?

**Comment by caliny97** [comment]
2.8rc2
thanks

**Comment by JasonB42** [comment]
I have also encountered this problem. It shows up as an infinite table not loading additional records after the initial population, with the console being spammed as above. 

The problem comes from InfiniteDataView:213
```
JQueryExtension.$(tableBody).scrollY(name, (e, scroll) ->  onScrollY(e));
```

Removing the lamba does not fix the problem, aka:
```
JQueryExtension.$(tableBody).scrollY(name, new FuncRet2<Event, String>() {
	@Override
	public Object call(Event e, String scroll) {
		return onScrollY(e);
	}
});
```

However, if you remove the JQueryExtension, it appears to work.
```
$(tableBody).on("scroll.infdataviewtest", (e) ->  onScrollY(e));
```
Please let me know if there is anything else I can do to help track down the source of this problem. 


Versions:
- GWT: 2.8.0
- gwt-material: 2.0-SNAPSHOT 
- gwt-material-table: 1.0-rc1
- gwt-material-query: 1.0-rc1
- com.github.gwtmaterialdesign.gwt-material: 2.0-SNAPSHOT

**Comment by BenDol** [comment]
Can you provide the exception details?

**Comment by JasonB42** [comment]
When you scroll down the infinite data view, the browser spams the console with: "**Uncaught TypeError: Cannot read property 'material' of undefined(…)**". The problem comes from a reference to "**$wnd.gwt.material.design.jquery.client.api.jQuery**". I have manually verified that **$wnd.gwt** is null.

Doing a quick grep, it looks like this is the only reference to **$wnd.gwt** I can find in the old generated code output. The changes above remove the reference in the generated output. Finally, this does not happen in superDevMode, only after being generated and deployed.

**Comment by BenDol** [comment]
Thanks for the thorough investigation, I will look into the issue now.

**Comment by BenDol** [comment]
Resolved the issue in the `release_1.0` branch, can you confirm that its resolved?

**Comment by JasonB42** [comment]
@BenDol Everything look good. Thank you for the quick turnaround!

**Comment by BenDol** [comment]
:+1:
